import { Question, Resource, Exam, Word } from '../types';

// --- Questions ---
export const INITIAL_QUESTIONS: Question[] = [];

// --- Resources ---
export const INITIAL_RESOURCES: Resource[] = [];

// --- Exams ---
export const INITIAL_EXAMS: Exam[] = [];

// --- Word Database (Level 3-6 Academic/Professional) ---
export const WORD_DATABASE: Word[] = [
    // LEVEL 3 (Basic Academic / General)
    { id: 101, en: 'Analyze', zh: '分析', level: 3 },
    { id: 102, en: 'Approach', zh: '方法/途徑', level: 3 },
    { id: 103, en: 'Area', zh: '區域/領域', level: 3 },
    { id: 104, en: 'Assess', zh: '評估', level: 3 },
    { id: 105, en: 'Assume', zh: '假設', level: 3 },
    { id: 106, en: 'Authority', zh: '權威/當局', level: 3 },
    { id: 107, en: 'Available', zh: '可用的', level: 3 },
    { id: 108, en: 'Benefit', zh: '益處', level: 3 },
    { id: 109, en: 'Concept', zh: '概念', level: 3 },
    { id: 110, en: 'Consist', zh: '組成', level: 3 },
    { id: 111, en: 'Context', zh: '情境/上下文', level: 3 },
    { id: 112, en: 'Create', zh: '創造', level: 3 },
    { id: 113, en: 'Data', zh: '資料', level: 3 },
    { id: 114, en: 'Define', zh: '定義', level: 3 },
    { id: 115, en: 'Derive', zh: '起源於/導出', level: 3 },
    { id: 116, en: 'Distribute', zh: '分發/分佈', level: 3 },
    { id: 117, en: 'Economy', zh: '經濟', level: 3 },
    { id: 118, en: 'Environment', zh: '環境', level: 3 },
    { id: 119, en: 'Establish', zh: '建立', level: 3 },
    { id: 120, en: 'Estimate', zh: '估計', level: 3 },
    { id: 121, en: 'Evidence', zh: '證據', level: 3 },
    { id: 122, en: 'Finance', zh: '財務', level: 3 },
    { id: 123, en: 'Formula', zh: '公式', level: 3 },
    { id: 124, en: 'Function', zh: '功能/函數', level: 3 },
    { id: 125, en: 'Identify', zh: '識別', level: 3 },
    { id: 126, en: 'Income', zh: '收入', level: 3 },
    { id: 127, en: 'Indicate', zh: '指出', level: 3 },
    { id: 128, en: 'Individual', zh: '個人的', level: 3 },
    { id: 129, en: 'Interpret', zh: '詮釋', level: 3 },
    { id: 130, en: 'Involve', zh: '涉及', level: 3 },
    { id: 131, en: 'Issue', zh: '議題', level: 3 },
    { id: 132, en: 'Labor', zh: '勞力', level: 3 },
    { id: 133, en: 'Legal', zh: '法律的', level: 3 },
    { id: 134, en: 'Legislate', zh: '立法', level: 3 },
    { id: 135, en: 'Major', zh: '主要的', level: 3 },
    { id: 136, en: 'Method', zh: '方法', level: 3 },
    { id: 137, en: 'Occur', zh: '發生', level: 3 },
    { id: 138, en: 'Percent', zh: '百分比', level: 3 },
    { id: 139, en: 'Period', zh: '時期', level: 3 },
    { id: 140, en: 'Policy', zh: '政策', level: 3 },

    // LEVEL 4 (Intermediate Academic)
    { id: 201, en: 'Principle', zh: '原則', level: 4 },
    { id: 202, en: 'Procedure', zh: '程序', level: 4 },
    { id: 203, en: 'Process', zh: '過程', level: 4 },
    { id: 204, en: 'Require', zh: '需要', level: 4 },
    { id: 205, en: 'Research', zh: '研究', level: 4 },
    { id: 206, en: 'Respond', zh: '回應', level: 4 },
    { id: 207, en: 'Role', zh: '角色', level: 4 },
    { id: 208, en: 'Section', zh: '部分', level: 4 },
    { id: 209, en: 'Sector', zh: '部門', level: 4 },
    { id: 210, en: 'Significant', zh: '顯著的', level: 4 },
    { id: 211, en: 'Similar', zh: '相似的', level: 4 },
    { id: 212, en: 'Source', zh: '來源', level: 4 },
    { id: 213, en: 'Specific', zh: '特定的', level: 4 },
    { id: 214, en: 'Structure', zh: '結構', level: 4 },
    { id: 215, en: 'Theory', zh: '理論', level: 4 },
    { id: 216, en: 'Vary', zh: '變化', level: 4 },
    { id: 217, en: 'Achieve', zh: '達成', level: 4 },
    { id: 218, en: 'Acquire', zh: '獲得', level: 4 },
    { id: 219, en: 'Administer', zh: '管理', level: 4 },
    { id: 220, en: 'Affect', zh: '影響', level: 4 },
    { id: 221, en: 'Appropriate', zh: '適當的', level: 4 },
    { id: 222, en: 'Aspect', zh: '方面', level: 4 },
    { id: 223, en: 'Assist', zh: '協助', level: 4 },
    { id: 224, en: 'Category', zh: '類別', level: 4 },
    { id: 225, en: 'Chapter', zh: '章節', level: 4 },
    { id: 226, en: 'Commission', zh: '委員會', level: 4 },
    { id: 227, en: 'Community', zh: '社群', level: 4 },
    { id: 228, en: 'Complex', zh: '複雜的', level: 4 },
    { id: 229, en: 'Compute', zh: '計算', level: 4 },
    { id: 230, en: 'Conclusion', zh: '結論', level: 4 },
    { id: 231, en: 'Conduct', zh: '進行/傳導', level: 4 },
    { id: 232, en: 'Sequence', zh: '順序', level: 4 },
    { id: 233, en: 'Series', zh: '系列', level: 4 },
    { id: 234, en: 'Status', zh: '狀態', level: 4 },
    { id: 235, en: 'Strategy', zh: '策略', level: 4 },

    // LEVEL 5 (Advanced Academic)
    { id: 301, en: 'Consequent', zh: '隨之發生的', level: 5 },
    { id: 302, en: 'Construct', zh: '建造/構念', level: 5 },
    { id: 303, en: 'Consume', zh: '消耗', level: 5 },
    { id: 304, en: 'Credit', zh: '信用/學分', level: 5 },
    { id: 305, en: 'Culture', zh: '文化', level: 5 },
    { id: 306, en: 'Design', zh: '設計', level: 5 },
    { id: 307, en: 'Distinct', zh: '獨特的', level: 5 },
    { id: 308, en: 'Element', zh: '元素', level: 5 },
    { id: 309, en: 'Equate', zh: '使相等', level: 5 },
    { id: 310, en: 'Evaluate', zh: '評估', level: 5 },
    { id: 311, en: 'Feature', zh: '特徵', level: 5 },
    { id: 312, en: 'Final', zh: '最後的', level: 5 },
    { id: 313, en: 'Focus', zh: '焦點', level: 5 },
    { id: 314, en: 'Impact', zh: '衝擊/影響', level: 5 },
    { id: 315, en: 'Injure', zh: '受傷', level: 5 },
    { id: 316, en: 'Institute', zh: '機構/制定', level: 5 },
    { id: 317, en: 'Invest', zh: '投資', level: 5 },
    { id: 318, en: 'Item', zh: '項目', level: 5 },
    { id: 319, en: 'Journal', zh: '期刊/日誌', level: 5 },
    { id: 320, en: 'Maintain', zh: '維持', level: 5 },
    { id: 321, en: 'Normal', zh: '正常的', level: 5 },
    { id: 322, en: 'Obtain', zh: '獲得', level: 5 },
    { id: 323, en: 'Participate', zh: '參與', level: 5 },
    { id: 324, en: 'Perceive', zh: '察覺/感知', level: 5 },
    { id: 325, en: 'Positive', zh: '正向的', level: 5 },
    { id: 326, en: 'Potential', zh: '潛在的', level: 5 },
    { id: 327, en: 'Previous', zh: '先前的', level: 5 },
    { id: 328, en: 'Primary', zh: '主要的/初級的', level: 5 },
    { id: 329, en: 'Purchase', zh: '購買', level: 5 },
    { id: 330, en: 'Range', zh: '範圍', level: 5 },
    { id: 331, en: 'Region', zh: '地區', level: 5 },
    { id: 332, en: 'Regulate', zh: '調節/規範', level: 5 },
    { id: 333, en: 'Relevant', zh: '相關的', level: 5 },
    { id: 334, en: 'Resident', zh: '居民', level: 5 },
    { id: 335, en: 'Resource', zh: '資源', level: 5 },

    // LEVEL 6 (Professional / Expert)
    { id: 401, en: 'Abstract', zh: '抽象的', level: 6 },
    { id: 402, en: 'Accurate', zh: '準確的', level: 6 },
    { id: 403, en: 'Acknowledge', zh: '承認', level: 6 },
    { id: 404, en: 'Aggregate', zh: '總計/聚集', level: 6 },
    { id: 405, en: 'Allocate', zh: '分派', level: 6 },
    { id: 406, en: 'Assign', zh: '指派', level: 6 },
    { id: 407, en: 'Attach', zh: '附上', level: 6 },
    { id: 408, en: 'Author', zh: '作者', level: 6 },
    { id: 409, en: 'Bond', zh: '債券/結合', level: 6 },
    { id: 410, en: 'Brief', zh: '簡短的', level: 6 },
    { id: 411, en: 'Capable', zh: '有能力的', level: 6 },
    { id: 412, en: 'Cite', zh: '引用', level: 6 },
    { id: 413, en: 'Cooperate', zh: '合作', level: 6 },
    { id: 414, en: 'Discriminate', zh: '歧視/區別', level: 6 },
    { id: 415, en: 'Display', zh: '顯示', level: 6 },
    { id: 416, en: 'Diverse', zh: '多樣的', level: 6 },
    { id: 417, en: 'Domain', zh: '領域', level: 6 },
    { id: 418, en: 'Edit', zh: '編輯', level: 6 },
    { id: 419, en: 'Enhance', zh: '增強', level: 6 },
    { id: 420, en: 'Estate', zh: '地產/遺產', level: 6 },
    { id: 421, en: 'Exceed', zh: '超過', level: 6 },
    { id: 422, en: 'Expert', zh: '專家', level: 6 },
    { id: 423, en: 'Explicit', zh: '明確的', level: 6 },
    { id: 424, en: 'Federal', zh: '聯邦的', level: 6 },
    { id: 425, en: 'Fee', zh: '費用', level: 6 },
    { id: 426, en: 'Flexibility', zh: '靈活性', level: 6 },
    { id: 427, en: 'Furthermore', zh: '此外', level: 6 },
    { id: 428, en: 'Gender', zh: '性別', level: 6 },
    { id: 429, en: 'Ignorance', zh: '無知', level: 6 },
    { id: 430, en: 'Incentive', zh: '誘因/動機', level: 6 },
    { id: 431, en: 'Incidence', zh: '發生率', level: 6 },
    { id: 432, en: 'Incorporate', zh: '合併/包含', level: 6 },
    { id: 433, en: 'Index', zh: '索引/指數', level: 6 },
    { id: 434, en: 'Inhibit', zh: '抑制', level: 6 },
    { id: 435, en: 'Initiate', zh: '開始', level: 6 },
    { id: 436, en: 'Input', zh: '輸入', level: 6 },
    { id: 437, en: 'Instruct', zh: '指導', level: 6 },
    { id: 438, en: 'Intelligence', zh: '智力/情報', level: 6 },
    { id: 439, en: 'Interval', zh: '間隔', level: 6 },
    { id: 440, en: 'Lecture', zh: '講演', level: 6 },
    { id: 441, en: 'Migrate', zh: '遷移', level: 6 },
    { id: 442, en: 'Minimum', zh: '最小量', level: 6 },
    { id: 443, en: 'Ministry', zh: '部/內閣', level: 6 },
    { id: 444, en: 'Motive', zh: '動機', level: 6 },
    { id: 445, en: 'Neutral', zh: '中立的', level: 6 },
    { id: 446, en: 'Nevertheless', zh: '然而', level: 6 },
    { id: 447, en: 'Overseas', zh: '海外的', level: 6 },
    { id: 448, en: 'Precede', zh: '在...之前', level: 6 },
    { id: 449, en: 'Presume', zh: '假定', level: 6 },
    { id: 450, en: 'Rational', zh: '理性的', level: 6 }
];