import { Question, Resource, Exam, Word } from '../types';

// --- Questions ---
export const INITIAL_QUESTIONS: Question[] = [];

// --- Resources ---
export const INITIAL_RESOURCES: Resource[] = [];

// --- Exams ---
export const INITIAL_EXAMS: Exam[] = [];

// --- Word Database (Level 3-6 Academic/Professional) ---
export const WORD_DATABASE: Word[] = [
    // --- LEVEL 3 (Basic Academic / Life) ---
    { id: 101, en: 'Analyze', zh: '分析', level: 3 },
    { id: 102, en: 'Approach', zh: '方法/途徑', level: 3 },
    { id: 103, en: 'Area', zh: '區域/領域', level: 3 },
    { id: 104, en: 'Assess', zh: '評估', level: 3 },
    { id: 105, en: 'Assume', zh: '假設', level: 3 },
    { id: 106, en: 'Authority', zh: '權威/當局', level: 3 },
    { id: 107, en: 'Available', zh: '可用的', level: 3 },
    { id: 108, en: 'Benefit', zh: '益處', level: 3 },
    { id: 109, en: 'Concept', zh: '概念', level: 3 },
    { id: 110, en: 'Consist', zh: '組成', level: 3 },
    { id: 111, en: 'Context', zh: '情境/上下文', level: 3 },
    { id: 112, en: 'Create', zh: '創造', level: 3 },
    { id: 113, en: 'Data', zh: '資料', level: 3 },
    { id: 114, en: 'Define', zh: '定義', level: 3 },
    { id: 115, en: 'Derive', zh: '起源於/導出', level: 3 },
    { id: 116, en: 'Distribute', zh: '分發/分佈', level: 3 },
    { id: 117, en: 'Economy', zh: '經濟', level: 3 },
    { id: 118, en: 'Environment', zh: '環境', level: 3 },
    { id: 119, en: 'Establish', zh: '建立', level: 3 },
    { id: 120, en: 'Estimate', zh: '估計', level: 3 },
    { id: 121, en: 'Evidence', zh: '證據', level: 3 },
    { id: 122, en: 'Factor', zh: '因素', level: 3 },
    { id: 123, en: 'Finance', zh: '財務', level: 3 },
    { id: 124, en: 'Formula', zh: '公式', level: 3 },
    { id: 125, en: 'Function', zh: '功能', level: 3 },
    { id: 126, en: 'Identify', zh: '識別', level: 3 },
    { id: 127, en: 'Income', zh: '收入', level: 3 },
    { id: 128, en: 'Indicate', zh: '指出', level: 3 },
    { id: 129, en: 'Individual', zh: '個人的', level: 3 },
    { id: 130, en: 'Interpret', zh: '詮釋', level: 3 },
    { id: 131, en: 'Involve', zh: '涉及/包含', level: 3 },
    { id: 132, en: 'Issue', zh: '議題/發行', level: 3 },
    { id: 133, en: 'Labor', zh: '勞工', level: 3 },
    { id: 134, en: 'Legal', zh: '法律的', level: 3 },
    { id: 135, en: 'Major', zh: '主要的', level: 3 },
    { id: 136, en: 'Method', zh: '方法', level: 3 },
    { id: 137, en: 'Occur', zh: '發生', level: 3 },
    { id: 138, en: 'Percent', zh: '百分比', level: 3 },
    { id: 139, en: 'Period', zh: '期間', level: 3 },
    { id: 140, en: 'Policy', zh: '政策', level: 3 },

    // --- LEVEL 4 (Advanced Life / Pre-Academic) ---
    { id: 201, en: 'Achieve', zh: '達成', level: 4 },
    { id: 202, en: 'Acquire', zh: '獲得', level: 4 },
    { id: 203, en: 'Administrate', zh: '管理', level: 4 },
    { id: 204, en: 'Affect', zh: '影響', level: 4 },
    { id: 205, en: 'Appropriate', zh: '適當的', level: 4 },
    { id: 206, en: 'Aspect', zh: '方面', level: 4 },
    { id: 207, en: 'Assist', zh: '協助', level: 4 },
    { id: 208, en: 'Category', zh: '類別', level: 4 },
    { id: 209, en: 'Chapter', zh: '章節', level: 4 },
    { id: 210, en: 'Commission', zh: '佣金/委員會', level: 4 },
    { id: 211, en: 'Community', zh: '社群', level: 4 },
    { id: 212, en: 'Complex', zh: '複雜的', level: 4 },
    { id: 213, en: 'Compute', zh: '計算', level: 4 },
    { id: 214, en: 'Conclude', zh: '下結論', level: 4 },
    { id: 215, en: 'Conduct', zh: '引導/進行', level: 4 },
    { id: 216, en: 'Consequent', zh: '隨之發生的', level: 4 },
    { id: 217, en: 'Construct', zh: '建造', level: 4 },
    { id: 218, en: 'Consume', zh: '消耗', level: 4 },
    { id: 219, en: 'Credit', zh: '信用', level: 4 },
    { id: 220, en: 'Culture', zh: '文化', level: 4 },
    { id: 221, en: 'Design', zh: '設計', level: 4 },
    { id: 222, en: 'Distinct', zh: '獨特的', level: 4 },
    { id: 223, en: 'Element', zh: '要素', level: 4 },
    { id: 224, en: 'Equate', zh: '使相等', level: 4 },
    { id: 225, en: 'Evaluate', zh: '評估', level: 4 },
    { id: 226, en: 'Feature', zh: '特徵', level: 4 },
    { id: 227, en: 'Final', zh: '最後的', level: 4 },
    { id: 228, en: 'Focus', zh: '焦點', level: 4 },
    { id: 229, en: 'Impact', zh: '衝擊', level: 4 },
    { id: 230, en: 'Injure', zh: '受傷', level: 4 },
    { id: 231, en: 'Institute', zh: '機構/學院', level: 4 },
    { id: 232, en: 'Invest', zh: '投資', level: 4 },
    { id: 233, en: 'Item', zh: '項目', level: 4 },
    { id: 234, en: 'Journal', zh: '期刊/日誌', level: 4 },
    { id: 235, en: 'Maintain', zh: '維持', level: 4 },
    { id: 236, en: 'Normal', zh: '正常的', level: 4 },
    { id: 237, en: 'Obtain', zh: '獲得', level: 4 },
    { id: 238, en: 'Participate', zh: '參與', level: 4 },
    { id: 239, en: 'Perceive', zh: '察覺/感知', level: 4 },
    { id: 240, en: 'Positive', zh: '正面的', level: 4 },

    // --- LEVEL 5 (Academic / Professional) ---
    { id: 301, en: 'Alternative', zh: '替代的', level: 5 },
    { id: 302, en: 'Circumstance', zh: '情況', level: 5 },
    { id: 303, en: 'Comment', zh: '評論', level: 5 },
    { id: 304, en: 'Compensate', zh: '補償', level: 5 },
    { id: 305, en: 'Component', zh: '零件/成分', level: 5 },
    { id: 306, en: 'Consent', zh: '同意', level: 5 },
    { id: 307, en: 'Considerable', zh: '相當大的', level: 5 },
    { id: 308, en: 'Constant', zh: '持續的', level: 5 },
    { id: 309, en: 'Constrain', zh: '限制/強迫', level: 5 },
    { id: 310, en: 'Contribute', zh: '貢獻', level: 5 },
    { id: 311, en: 'Convene', zh: '召集/集合', level: 5 },
    { id: 312, en: 'Coordinate', zh: '協調', level: 5 },
    { id: 313, en: 'Core', zh: '核心', level: 5 },
    { id: 314, en: 'Corporate', zh: '企業的', level: 5 },
    { id: 315, en: 'Correspond', zh: '符合/通信', level: 5 },
    { id: 316, en: 'Criteria', zh: '標準(複數)', level: 5 },
    { id: 317, en: 'Deduce', zh: '推論', level: 5 },
    { id: 318, en: 'Demonstrate', zh: '示範/證明', level: 5 },
    { id: 319, en: 'Document', zh: '文件', level: 5 },
    { id: 320, en: 'Dominate', zh: '支配', level: 5 },
    { id: 321, en: 'Emphasis', zh: '強調', level: 5 },
    { id: 322, en: 'Ensure', zh: '確保', level: 5 },
    { id: 323, en: 'Exclude', zh: '排除', level: 5 },
    { id: 324, en: 'Framework', zh: '架構', level: 5 },
    { id: 325, en: 'Fund', zh: '資金', level: 5 },
    { id: 326, en: 'Illustrate', zh: '舉例說明', level: 5 },
    { id: 327, en: 'Immigrate', zh: '移民', level: 5 },
    { id: 328, en: 'Imply', zh: '暗示', level: 5 },
    { id: 329, en: 'Initial', zh: '最初的', level: 5 },
    { id: 330, en: 'Instance', zh: '例子', level: 5 },
    { id: 331, en: 'Interact', zh: '互動', level: 5 },
    { id: 332, en: 'Justify', zh: '辯解', level: 5 },
    { id: 333, en: 'Layer', zh: '層次', level: 5 },
    { id: 334, en: 'Link', zh: '連結', level: 5 },
    { id: 335, en: 'Locate', zh: '定位', level: 5 },
    { id: 336, en: 'Maximise', zh: '最大化', level: 5 },
    { id: 337, en: 'Minor', zh: '次要的', level: 5 },
    { id: 338, en: 'Negate', zh: '否定', level: 5 },
    { id: 339, en: 'Outcome', zh: '結果', level: 5 },
    { id: 340, en: 'Partner', zh: '夥伴', level: 5 },

    // --- LEVEL 6 (Advanced Academic / Abstract) ---
    { id: 401, en: 'Interaction', zh: '互動', level: 6 },
    { id: 402, en: 'Justify', zh: '證明...是正當的', level: 6 },
    { id: 403, en: 'Layer', zh: '層', level: 6 },
    { id: 404, en: 'Link', zh: '連結', level: 6 },
    { id: 405, en: 'Locate', zh: '位於/定位', level: 6 },
    { id: 406, en: 'Maximize', zh: '最大化', level: 6 },
    { id: 407, en: 'Minor', zh: '次要的/未成年', level: 6 },
    { id: 408, en: 'Negate', zh: '否定/取消', level: 6 },
    { id: 409, en: 'Outcome', zh: '結果', level: 6 },
    { id: 410, en: 'Partner', zh: '夥伴', level: 6 },
    { id: 411, en: 'Philosophy', zh: '哲學', level: 6 },
    { id: 412, en: 'Physical', zh: '身體的/物理的', level: 6 },
    { id: 413, en: 'Proportion', zh: '比例', level: 6 },
    { id: 414, en: 'Publish', zh: '出版', level: 6 },
    { id: 415, en: 'React', zh: '反應', level: 6 },
    { id: 416, en: 'Register', zh: '註冊', level: 6 },
    { id: 417, en: 'Rely', zh: '依賴', level: 6 },
    { id: 418, en: 'Remove', zh: '移除', level: 6 },
    { id: 419, en: 'Scheme', zh: '計畫/方案', level: 6 },
    { id: 420, en: 'Sequence', zh: '順序', level: 6 },
    { id: 421, en: 'Sex', zh: '性別', level: 6 },
    { id: 422, en: 'Shift', zh: '轉移/輪班', level: 6 },
    { id: 423, en: 'Specify', zh: '具體說明', level: 6 },
    { id: 424, en: 'Sufficient', zh: '充足的', level: 6 },
    { id: 425, en: 'Task', zh: '任務', level: 6 },
    { id: 426, en: 'Technical', zh: '技術性的', level: 6 },
    { id: 427, en: 'Technique', zh: '技巧', level: 6 },
    { id: 428, en: 'Technology', zh: '科技', level: 6 },
    { id: 429, en: 'Valid', zh: '有效的', level: 6 },
    { id: 430, en: 'Volume', zh: '體積/音量/卷', level: 6 },
    { id: 431, en: 'Access', zh: '存取/通道', level: 6 },
    { id: 432, en: 'Adequate', zh: '足夠的', level: 6 },
    { id: 433, en: 'Annual', zh: '年度的', level: 6 },
    { id: 434, en: 'Apparent', zh: '明顯的', level: 6 },
    { id: 435, en: 'Approximate', zh: '大約的', level: 6 },
    { id: 436, en: 'Attitude', zh: '態度', level: 6 },
    { id: 437, en: 'Attribute', zh: '歸因於/屬性', level: 6 },
    { id: 438, en: 'Civil', zh: '公民的/民用的', level: 6 },
    { id: 439, en: 'Code', zh: '代碼/規範', level: 6 },
    { id: 440, en: 'Commit', zh: '承諾/犯罪', level: 6 },
    { id: 441, en: 'Concentrate', zh: '專注', level: 6 },
    { id: 442, en: 'Confer', zh: '商討/授予', level: 6 },
    { id: 443, en: 'Contrast', zh: '對比', level: 6 },
    { id: 444, en: 'Cycle', zh: '循環/週期', level: 6 },
    { id: 445, en: 'Debate', zh: '辯論', level: 6 },
    { id: 446, en: 'Despite', zh: '儘管', level: 6 },
    { id: 447, en: 'Dimension', zh: '維度/尺寸', level: 6 },
    { id: 448, en: 'Domestic', zh: '國內的/家庭的', level: 6 },
    { id: 449, en: 'Emerge', zh: '浮現/出現', level: 6 },
    { id: 450, en: 'Error', zh: '錯誤', level: 6 },
    { id: 451, en: 'Ethnic', zh: '種族的', level: 6 },
    { id: 452, en: 'Goal', zh: '目標', level: 6 },
    { id: 453, en: 'Grant', zh: '准許/補助金', level: 6 },
    { id: 454, en: 'Hence', zh: '因此', level: 6 },
    { id: 455, en: 'Hypothesis', zh: '假說', level: 6 },
    { id: 456, en: 'Implement', zh: '實施', level: 6 },
    { id: 457, en: 'Implicate', zh: '牽連/意指', level: 6 },
    { id: 458, en: 'Impose', zh: '強加/徵收', level: 6 },
    { id: 459, en: 'Integrate', zh: '整合', level: 6 },
    { id: 460, en: 'Internal', zh: '內部的', level: 6 }
];