
import { Question, Resource, Exam, Word } from '../types';

// --- Questions ---
export const INITIAL_QUESTIONS: Question[] = [];

// --- Resources ---
export const INITIAL_RESOURCES: Resource[] = [];

// --- Exams ---
export const INITIAL_EXAMS: Exam[] = [];

// --- Word Database (Expanded for replayability) ---
// Levels: 3 (Basic), 4 (Intermediate), 5 (Advanced), 6 (Expert/Abstract)
// Added examples and part of speech for practice mode
export const WORD_DATABASE: Word[] = [
    // --- LEVEL 3 (Basic Academic / Life) ---
    { id: 101, en: 'Analyze', zh: '分析', level: 3, partOfSpeech: 'v.', example: 'We need to analyze the data.' },
    { id: 102, en: 'Approach', zh: '方法/接近', level: 3, partOfSpeech: 'n./v.', example: 'He decided to approach the problem differently.' },
    { id: 103, en: 'Area', zh: '區域/領域', level: 3, partOfSpeech: 'n.', example: 'This is a restricted area.' },
    { id: 104, en: 'Assess', zh: '評估', level: 3, partOfSpeech: 'v.', example: 'Tests are used to assess student progress.' },
    { id: 105, en: 'Assume', zh: '假設', level: 3, partOfSpeech: 'v.', example: 'I assume you are tired after the trip.' },
    { id: 106, en: 'Authority', zh: '權威', level: 3, partOfSpeech: 'n.', example: 'He is an authority on history.' },
    { id: 107, en: 'Available', zh: '可用的', level: 3, partOfSpeech: 'adj.', example: 'Tickets are available online.' },
    { id: 108, en: 'Benefit', zh: '益處', level: 3, partOfSpeech: 'n.', example: 'Exercise has many benefits.' },
    { id: 109, en: 'Concept', zh: '概念', level: 3, partOfSpeech: 'n.', example: 'The concept of time travel is fascinating.' },
    { id: 110, en: 'Consist', zh: '組成', level: 3, partOfSpeech: 'v.', example: 'The team consists of five members.' },
    { id: 111, en: 'Context', zh: '情境/上下文', level: 3, partOfSpeech: 'n.', example: 'You must read the sentence in context.' },
    { id: 112, en: 'Create', zh: '創造', level: 3, partOfSpeech: 'v.', example: 'Artists create beauty.' },
    { id: 113, en: 'Data', zh: '資料', level: 3, partOfSpeech: 'n.', example: 'The data shows a clear trend.' },
    { id: 114, en: 'Define', zh: '定義', level: 3, partOfSpeech: 'v.', example: 'It is hard to define love.' },
    { id: 115, en: 'Derive', zh: '導出/起源', level: 3, partOfSpeech: 'v.', example: 'Many English words are derived from Latin.' },
    { id: 116, en: 'Distribute', zh: '分發', level: 3, partOfSpeech: 'v.', example: 'The teacher distributed the papers.' },
    { id: 117, en: 'Economy', zh: '經濟', level: 3, partOfSpeech: 'n.', example: 'The global economy is recovering.' },
    { id: 118, en: 'Environment', zh: '環境', level: 3, partOfSpeech: 'n.', example: 'We must protect the environment.' },
    { id: 119, en: 'Establish', zh: '建立', level: 3, partOfSpeech: 'v.', example: 'The school was established in 1990.' },
    { id: 120, en: 'Estimate', zh: '估計', level: 3, partOfSpeech: 'v.', example: 'We estimate the cost to be $50.' },
    { id: 121, en: 'Evidence', zh: '證據', level: 3, partOfSpeech: 'n.', example: 'There is no evidence of a crime.' },
    { id: 122, en: 'Factor', zh: '因素', level: 3, partOfSpeech: 'n.', example: 'Price is a major factor.' },
    { id: 123, en: 'Finance', zh: '財務', level: 3, partOfSpeech: 'n.', example: 'He works in finance.' },
    { id: 124, en: 'Formula', zh: '公式', level: 3, partOfSpeech: 'n.', example: 'Do you know the formula for area?' },
    { id: 125, en: 'Function', zh: '功能', level: 3, partOfSpeech: 'n.', example: 'The main function of the heart is to pump blood.' },
    { id: 126, en: 'Identify', zh: '識別', level: 3, partOfSpeech: 'v.', example: 'Can you identify this plant?' },
    { id: 127, en: 'Income', zh: '收入', level: 3, partOfSpeech: 'n.', example: 'His annual income increased.' },
    { id: 128, en: 'Indicate', zh: '指出', level: 3, partOfSpeech: 'v.', example: 'The map indicates where the treasure is.' },
    { id: 129, en: 'Individual', zh: '個人的', level: 3, partOfSpeech: 'adj./n.', example: 'Each individual has rights.' },
    { id: 130, en: 'Interpret', zh: '詮釋', level: 3, partOfSpeech: 'v.', example: 'How do you interpret this poem?' },
    { id: 131, en: 'Involve', zh: '涉及', level: 3, partOfSpeech: 'v.', example: 'The job involves travel.' },
    { id: 132, en: 'Issue', zh: '議題', level: 3, partOfSpeech: 'n.', example: 'Pollution is a global issue.' },
    { id: 133, en: 'Labor', zh: '勞工', level: 3, partOfSpeech: 'n.', example: 'Manual labor can be tiring.' },
    { id: 134, en: 'Legal', zh: '法律的', level: 3, partOfSpeech: 'adj.', example: 'Seek legal advice.' },
    { id: 135, en: 'Major', zh: '主要的', level: 3, partOfSpeech: 'adj.', example: 'This is a major problem.' },
    { id: 136, en: 'Method', zh: '方法', level: 3, partOfSpeech: 'n.', example: 'This is a new teaching method.' },
    { id: 137, en: 'Occur', zh: '發生', level: 3, partOfSpeech: 'v.', example: 'When did the accident occur?' },
    { id: 138, en: 'Percent', zh: '百分比', level: 3, partOfSpeech: 'n.', example: 'Fifty percent of the class passed.' },
    { id: 139, en: 'Period', zh: '期間', level: 3, partOfSpeech: 'n.', example: 'A period of silence.' },
    { id: 140, en: 'Policy', zh: '政策', level: 3, partOfSpeech: 'n.', example: 'The company has a strict policy.' },
    { id: 141, en: 'Principle', zh: '原則', level: 3, partOfSpeech: 'n.', example: 'He is a man of principle.' },
    { id: 142, en: 'Proceed', zh: '繼續進行', level: 3, partOfSpeech: 'v.', example: 'Please proceed with your work.' },
    { id: 143, en: 'Process', zh: '過程', level: 3, partOfSpeech: 'n.', example: 'Learning is a long process.' },
    { id: 144, en: 'Require', zh: '要求', level: 3, partOfSpeech: 'v.', example: 'Plants require water.' },
    { id: 145, en: 'Research', zh: '研究', level: 3, partOfSpeech: 'n./v.', example: 'Scientific research is important.' },
    { id: 146, en: 'Respond', zh: '回應', level: 3, partOfSpeech: 'v.', example: 'Please respond to my email.' },
    { id: 147, en: 'Role', zh: '角色', level: 3, partOfSpeech: 'n.', example: 'She played a key role.' },
    { id: 148, en: 'Section', zh: '部分', level: 3, partOfSpeech: 'n.', example: 'Read the first section.' },
    { id: 149, en: 'Sector', zh: '部門', level: 3, partOfSpeech: 'n.', example: 'The private sector is growing.' },
    { id: 150, en: 'Significant', zh: '顯著的', level: 3, partOfSpeech: 'adj.', example: 'There was a significant change.' },
    { id: 151, en: 'Similar', zh: '相似的', level: 3, partOfSpeech: 'adj.', example: 'We have similar tastes.' },
    { id: 152, en: 'Source', zh: '來源', level: 3, partOfSpeech: 'n.', example: 'The source of the river.' },
    { id: 153, en: 'Specific', zh: '特定的', level: 3, partOfSpeech: 'adj.', example: 'Be specific about what you want.' },
    { id: 154, en: 'Structure', zh: '結構', level: 3, partOfSpeech: 'n.', example: 'The structure of the building is safe.' },
    { id: 155, en: 'Theory', zh: '理論', level: 3, partOfSpeech: 'n.', example: 'Darwin\'s theory of evolution.' },
    { id: 156, en: 'Vary', zh: '變化', level: 3, partOfSpeech: 'v.', example: 'Prices vary from shop to shop.' },
    { id: 157, en: 'Client', zh: '客戶', level: 3, partOfSpeech: 'n.', example: 'He is meeting a client.' },
    { id: 158, en: 'Compare', zh: '比較', level: 3, partOfSpeech: 'v.', example: 'Compare the two pictures.' },
    { id: 159, en: 'Contrast', zh: '對比', level: 3, partOfSpeech: 'n./v.', example: 'The contrast between rich and poor.' },
    { id: 160, en: 'Describe', zh: '描述', level: 3, partOfSpeech: 'v.', example: 'Can you describe the thief?' },
    { id: 161, en: 'Develop', zh: '發展', level: 3, partOfSpeech: 'v.', example: 'The city is developing rapidly.' },
    { id: 162, en: 'Difference', zh: '差異', level: 3, partOfSpeech: 'n.', example: 'What is the difference?' },
    { id: 163, en: 'Direct', zh: '直接的', level: 3, partOfSpeech: 'adj.', example: 'A direct flight.' },
    { id: 164, en: 'Display', zh: '展示', level: 3, partOfSpeech: 'v.', example: 'The goods are on display.' },
    { id: 165, en: 'Economic', zh: '經濟的', level: 3, partOfSpeech: 'adj.', example: 'Economic growth.' },
    { id: 166, en: 'Edit', zh: '編輯', level: 3, partOfSpeech: 'v.', example: 'Edit the document.' },
    { id: 167, en: 'Effect', zh: '效果', level: 3, partOfSpeech: 'n.', example: 'The medicine had a good effect.' },
    { id: 168, en: 'Election', zh: '選舉', level: 3, partOfSpeech: 'n.', example: 'The presidential election.' },
    { id: 169, en: 'Energy', zh: '能量', level: 3, partOfSpeech: 'n.', example: 'Solar energy.' },
    { id: 170, en: 'Example', zh: '例子', level: 3, partOfSpeech: 'n.', example: 'For example.' },

    // --- LEVEL 4 (Intermediate) ---
    { id: 201, en: 'Achieve', zh: '達成', level: 4, partOfSpeech: 'v.', example: 'She achieved her goal.' },
    { id: 202, en: 'Acquire', zh: '獲得', level: 4, partOfSpeech: 'v.', example: 'Acquire knowledge.' },
    { id: 203, en: 'Administrate', zh: '管理', level: 4, partOfSpeech: 'v.', example: 'Administrate the program.' },
    { id: 204, en: 'Affect', zh: '影響', level: 4, partOfSpeech: 'v.', example: 'The weather affects my mood.' },
    { id: 205, en: 'Appropriate', zh: '適當的', level: 4, partOfSpeech: 'adj.', example: 'Wear appropriate clothes.' },
    // ... Keeping rest without detailed examples to save space, assuming logic handles optional fields
    { id: 206, en: 'Aspect', zh: '方面', level: 4 },
    { id: 207, en: 'Assist', zh: '協助', level: 4 },
    { id: 208, en: 'Category', zh: '類別', level: 4 },
    { id: 209, en: 'Chapter', zh: '章節', level: 4 },
    { id: 210, en: 'Commission', zh: '委員會/佣金', level: 4 },
    { id: 211, en: 'Community', zh: '社群', level: 4 },
    { id: 212, en: 'Complex', zh: '複雜的', level: 4 },
    { id: 213, en: 'Compute', zh: '計算', level: 4 },
    { id: 214, en: 'Conclude', zh: '下結論', level: 4 },
    { id: 215, en: 'Conduct', zh: '進行/傳導', level: 4 },
    { id: 216, en: 'Consequent', zh: '隨之發生的', level: 4 },
    { id: 217, en: 'Construct', zh: '建造', level: 4 },
    { id: 218, en: 'Consume', zh: '消耗', level: 4 },
    { id: 219, en: 'Credit', zh: '信用/學分', level: 4 },
    { id: 220, en: 'Culture', zh: '文化', level: 4 },
    { id: 221, en: 'Design', zh: '設計', level: 4 },
    { id: 222, en: 'Distinct', zh: '獨特的', level: 4 },
    { id: 223, en: 'Element', zh: '要素', level: 4 },
    { id: 224, en: 'Equate', zh: '使相等', level: 4 },
    { id: 225, en: 'Evaluate', zh: '評估', level: 4 },
    { id: 226, en: 'Feature', zh: '特徵', level: 4 },
    { id: 227, en: 'Final', zh: '最後的', level: 4 },
    { id: 228, en: 'Focus', zh: '焦點', level: 4 },
    { id: 229, en: 'Impact', zh: '衝擊', level: 4 },
    { id: 230, en: 'Injure', zh: '受傷', level: 4 },
    { id: 231, en: 'Institute', zh: '機構', level: 4 },
    { id: 232, en: 'Invest', zh: '投資', level: 4 },
    { id: 233, en: 'Item', zh: '項目', level: 4 },
    { id: 234, en: 'Journal', zh: '期刊', level: 4 },
    { id: 235, en: 'Maintain', zh: '維持', level: 4 },
    { id: 236, en: 'Normal', zh: '正常的', level: 4 },
    { id: 237, en: 'Obtain', zh: '獲得', level: 4 },
    { id: 238, en: 'Participate', zh: '參與', level: 4 },
    { id: 239, en: 'Perceive', zh: '察覺', level: 4 },
    { id: 240, en: 'Positive', zh: '正面的', level: 4 },
    { id: 241, en: 'Potential', zh: '潛在的', level: 4 },
    { id: 242, en: 'Previous', zh: '先前的', level: 4 },
    { id: 243, en: 'Primary', zh: '首要的', level: 4 },
    { id: 244, en: 'Purchase', zh: '購買', level: 4 },
    { id: 245, en: 'Range', zh: '範圍', level: 4 },
    { id: 246, en: 'Region', zh: '地區', level: 4 },
    { id: 247, en: 'Regulate', zh: '調節/規範', level: 4 },
    { id: 248, en: 'Relevant', zh: '相關的', level: 4 },
    { id: 249, en: 'Reside', zh: '居住', level: 4 },
    { id: 250, en: 'Resource', zh: '資源', level: 4 },
    { id: 251, en: 'Restrict', zh: '限制', level: 4 },
    { id: 252, en: 'Secure', zh: '安全的', level: 4 },
    { id: 253, en: 'Seek', zh: '尋找', level: 4 },
    { id: 254, en: 'Select', zh: '選擇', level: 4 },
    { id: 255, en: 'Site', zh: '地點', level: 4 },
    { id: 256, en: 'Strategy', zh: '策略', level: 4 },
    { id: 257, en: 'Survey', zh: '調查', level: 4 },
    { id: 258, en: 'Text', zh: '文本', level: 4 },
    { id: 259, en: 'Tradition', zh: '傳統', level: 4 },
    { id: 260, en: 'Transfer', zh: '轉移', level: 4 },

    // --- LEVEL 5 (Advanced) ---
    { id: 301, en: 'Alternative', zh: '替代的', level: 5 },
    { id: 302, en: 'Circumstance', zh: '情況', level: 5 },
    { id: 303, en: 'Comment', zh: '評論', level: 5 },
    { id: 304, en: 'Compensate', zh: '補償', level: 5 },
    { id: 305, en: 'Component', zh: '零件', level: 5 },
    { id: 306, en: 'Consent', zh: '同意', level: 5 },
    { id: 307, en: 'Considerable', zh: '相當大的', level: 5 },
    { id: 308, en: 'Constant', zh: '持續的', level: 5 },
    { id: 309, en: 'Constrain', zh: '限制/強迫', level: 5 },
    { id: 310, en: 'Contribute', zh: '貢獻', level: 5 },
    { id: 311, en: 'Convene', zh: '召集', level: 5 },
    { id: 312, en: 'Coordinate', zh: '協調', level: 5 },
    { id: 313, en: 'Core', zh: '核心', level: 5 },
    { id: 314, en: 'Corporate', zh: '企業的', level: 5 },
    { id: 315, en: 'Correspond', zh: '符合/通信', level: 5 },
    { id: 316, en: 'Criteria', zh: '標準', level: 5 },
    { id: 317, en: 'Deduce', zh: '推論', level: 5 },
    { id: 318, en: 'Demonstrate', zh: '示範/證明', level: 5 },
    { id: 319, en: 'Document', zh: '文件', level: 5 },
    { id: 320, en: 'Dominate', zh: '支配', level: 5 },
    { id: 321, en: 'Emphasis', zh: '強調', level: 5 },
    { id: 322, en: 'Ensure', zh: '確保', level: 5 },
    { id: 323, en: 'Exclude', zh: '排除', level: 5 },
    { id: 324, en: 'Framework', zh: '架構', level: 5 },
    { id: 325, en: 'Fund', zh: '資金', level: 5 },
    { id: 326, en: 'Illustrate', zh: '舉例說明', level: 5 },
    { id: 327, en: 'Immigrate', zh: '移民', level: 5 },
    { id: 328, en: 'Imply', zh: '暗示', level: 5 },
    { id: 329, en: 'Initial', zh: '最初的', level: 5 },
    { id: 330, en: 'Instance', zh: '例子', level: 5 },
    { id: 331, en: 'Interact', zh: '互動', level: 5 },
    { id: 332, en: 'Justify', zh: '辯解/證明正當', level: 5 },
    { id: 333, en: 'Layer', zh: '層次', level: 5 },
    { id: 334, en: 'Link', zh: '連結', level: 5 },
    { id: 335, en: 'Locate', zh: '定位', level: 5 },
    { id: 336, en: 'Maximise', zh: '最大化', level: 5 },
    { id: 337, en: 'Minor', zh: '次要的', level: 5 },
    { id: 338, en: 'Negate', zh: '否定', level: 5 },
    { id: 339, en: 'Outcome', zh: '結果', level: 5 },
    { id: 340, en: 'Partner', zh: '夥伴', level: 5 },
    { id: 341, en: 'Philosophy', zh: '哲學', level: 5 },
    { id: 342, en: 'Physical', zh: '物理的/身體的', level: 5 },
    { id: 343, en: 'Proportion', zh: '比例', level: 5 },
    { id: 344, en: 'Publish', zh: '出版', level: 5 },
    { id: 345, en: 'React', zh: '反應', level: 5 },
    { id: 346, en: 'Register', zh: '註冊', level: 5 },
    { id: 347, en: 'Rely', zh: '依賴', level: 5 },
    { id: 348, en: 'Remove', zh: '移除', level: 5 },
    { id: 349, en: 'Scheme', zh: '方案', level: 5 },
    { id: 350, en: 'Sequence', zh: '順序', level: 5 },
    { id: 351, en: 'Shift', zh: '轉移', level: 5 },
    { id: 352, en: 'Specify', zh: '具體說明', level: 5 },
    { id: 353, en: 'Sufficient', zh: '充足的', level: 5 },
    { id: 354, en: 'Task', zh: '任務', level: 5 },
    { id: 355, en: 'Technical', zh: '技術性的', level: 5 },
    { id: 356, en: 'Technique', zh: '技巧', level: 5 },
    { id: 357, en: 'Technology', zh: '科技', level: 5 },
    { id: 358, en: 'Valid', zh: '有效的', level: 5 },
    { id: 359, en: 'Volume', zh: '體積/音量', level: 5 },
    { id: 360, en: 'Access', zh: '存取', level: 5 },

    // --- LEVEL 6 (Expert) ---
    { id: 401, en: 'Interaction', zh: '互動', level: 6 },
    { id: 402, en: 'Justification', zh: '正當理由', level: 6 },
    { id: 403, en: 'Mechanism', zh: '機制', level: 6 },
    { id: 404, en: 'Obvious', zh: '明顯的', level: 6 },
    { id: 405, en: 'Occupy', zh: '佔據', level: 6 },
    { id: 406, en: 'Option', zh: '選項', level: 6 },
    { id: 407, en: 'Output', zh: '輸出', level: 6 },
    { id: 408, en: 'Overall', zh: '整體的', level: 6 },
    { id: 409, en: 'Parallel', zh: '平行的', level: 6 },
    { id: 410, en: 'Parameter', zh: '參數', level: 6 },
    { id: 411, en: 'Phase', zh: '階段', level: 6 },
    { id: 412, en: 'Predict', zh: '預測', level: 6 },
    { id: 413, en: 'Principal', zh: '主要的/校長', level: 6 },
    { id: 414, en: 'Prior', zh: '優先的', level: 6 },
    { id: 415, en: 'Professional', zh: '專業的', level: 6 },
    { id: 416, en: 'Project', zh: '計畫', level: 6 },
    { id: 417, en: 'Promote', zh: '促進/升遷', level: 6 },
    { id: 418, en: 'Regime', zh: '政權/體制', level: 6 },
    { id: 419, en: 'Resolve', zh: '解決/決心', level: 6 },
    { id: 420, en: 'Retain', zh: '保留', level: 6 },
    { id: 421, en: 'Series', zh: '系列', level: 6 },
    { id: 422, en: 'Statistic', zh: '統計數值', level: 6 },
    { id: 423, en: 'Status', zh: '地位/狀態', level: 6 },
    { id: 424, en: 'Stress', zh: '壓力', level: 6 },
    { id: 425, en: 'Subsequent', zh: '隨後的', level: 6 },
    { id: 426, en: 'Sum', zh: '總和', level: 6 },
    { id: 427, en: 'Summary', zh: '摘要', level: 6 },
    { id: 428, en: 'Undertake', zh: '承擔/著手', level: 6 },
    { id: 429, en: 'Academy', zh: '學院', level: 6 },
    { id: 430, en: 'Adjust', zh: '調整', level: 6 },
    { id: 431, en: 'Alter', zh: '改變', level: 6 },
    { id: 432, en: 'Amend', zh: '修正', level: 6 },
    { id: 433, en: 'Aware', zh: '意識到的', level: 6 },
    { id: 434, en: 'Capacity', zh: '容量/能力', level: 6 },
    { id: 435, en: 'Challenge', zh: '挑戰', level: 6 },
    { id: 436, en: 'Clause', zh: '條款/子句', level: 6 },
    { id: 437, en: 'Compound', zh: '化合物/混合', level: 6 },
    { id: 438, en: 'Conflict', zh: '衝突', level: 6 },
    { id: 439, en: 'Consult', zh: '諮詢', level: 6 },
    { id: 440, en: 'Contact', zh: '接觸', level: 6 },
    { id: 441, en: 'Decline', zh: '下降/拒絕', level: 6 },
    { id: 442, en: 'Discrete', zh: '離散的', level: 6 },
    { id: 443, en: 'Draft', zh: '草稿', level: 6 },
    { id: 444, en: 'Enable', zh: '使能夠', level: 6 },
    { id: 445, en: 'Enforce', zh: '執行/強制', level: 6 },
    { id: 446, en: 'Entity', zh: '實體', level: 6 },
    { id: 447, en: 'Equivalent', zh: '相等的', level: 6 },
    { id: 448, en: 'Evolve', zh: '演化', level: 6 },
    { id: 449, en: 'Expand', zh: '擴大', level: 6 },
    { id: 450, en: 'Expose', zh: '暴露', level: 6 },
    { id: 451, en: 'External', zh: '外部的', level: 6 },
    { id: 452, en: 'Facilitate', zh: '促進', level: 6 },
    { id: 453, en: 'Fundamental', zh: '基礎的', level: 6 },
    { id: 454, en: 'Generate', zh: '產生', level: 6 },
    { id: 455, en: 'Generation', zh: '世代', level: 6 },
    { id: 456, en: 'Image', zh: '形象/影像', level: 6 },
    { id: 457, en: 'Liberal', zh: '自由的/開明的', level: 6 },
    { id: 458, en: 'Licence', zh: '執照', level: 6 },
    { id: 459, en: 'Logic', zh: '邏輯', level: 6 },
    { id: 460, en: 'Margin', zh: '邊緣/利潤', level: 6 }
];
